apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterInput
metadata:
  labels:
    fluentbit.fluent.io/component: logging
    fluentbit.fluent.io/enabled: "true"
  name: fluentbit-application-input
spec:
  tail:
    db: /fluent-bit/tail/pos-application.db
    dbSync: Normal
    memBufLimit: 15MB
    parser: cri
    path: /var/log/containers/*application*.log
    excludePath: "/var/log/containers/fluent*.log"
    refreshIntervalSeconds: 10
    skipLongLines: true
    tag: application*
---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: fluentbit-application-output
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  match: application*
  alias: opensearch
  opensearch:
    host: vpc-esinfra-xprnqb6o7ptbsgklyzy6n6kvhm.eu-west-1.es.amazonaws.com
    port: 443
    httpUser:
      valueFrom:
        secretKeyRef: 
          key: user
          name: opensearchsecret02
    httpPassword:
      valueFrom:
        secretKeyRef: 
          key: password
          name: opensearchsecret02          
    generateID: true
    logstashPrefix: application
    logstashFormat: true
    timeKey: "@timestamp"
    tls:
      verify: false
--- 
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  labels:
    fluentbit.fluent.io/component: logging
    fluentbit.fluent.io/enabled: "true"
  name: fluentbit-application-filter
spec:
  filters:
  - kubernetes:
      annotations: false
      kubeCAFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      kubeTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubeURL: https://kubernetes.default.svc:443
      labels: false
      kubeTagPrefix: application.var.log.containers.
  - nest:
      addPrefix: kubernetes_
      nestedUnder: kubernetes
      operation: lift
  - modify:
      rules:
      - remove: stream
      - remove: kubernetes_pod_id
      - remove: kubernetes_host
      - remove: kubernetes_container_hash
  - nest:
      nestUnder: kubernetes
      operation: nest
      removePrefix: kubernetes_
      wildcard:
      - kubernetes_*
  match: application*    