apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-access-account
  annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::035528414329:role/eks-s3-edms-prod-eu-west-1-eks-03
automountServiceAccountToken: true

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: sm-access-account
  annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::035528414329:role/eks-sm-access-edms-prod-eu-west-1-eks-03
automountServiceAccountToken: true

