apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-access-account
  annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::653449238136:role/eks-s3-edms-nonprod-eu-west-1-eks-03
automountServiceAccountToken: true

