apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-access-account
  annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::733389991468:role/eks-s3-edms-prod-eu-west-1-eks-03
automountServiceAccountToken: true

