apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  storageClassName: efs-dynamic-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi 
